### PR TITLE
Upgraded related changes for JDOM2 support

### PR DESCRIPTION
**Pull request by Rahman14354**
Fix for
https://github.com/jaxen-xpath/jaxen/issues/2

JAXEN latest build dosen't support JDOM2, Need support for JDOM2.

https://github.com/hunterhacker/jdom/wiki/JDOM2-Migration-Issues

### CODE REVIEW

**Comment by elharo** [comment]
Yes, we should support JDOM2.
Is there anyway we can support JDOM 1 at the same time?

**Comment by elharo** [comment]
The current thinking is that individual model navigators (JDOM, JDOM2, XOM, etc.) belong with the model projects, not in jaxen core. That way JDOM doesn't have to pay for the cost of everyone else's navigators and vice versa. Also the project can keep the navigators in sync with their own releases. 

Could this code be added to JDOM2 instead?

**Comment by Rahman14354** [comment]
>>>Is there anyway we can support JDOM 1 at the same time?
It is bit thorny to maintenance both, IMO, for JDOM 1 support older version of JAXEN can be used.


>>>The current thinking is that individual model navigators (JDOM, JDOM2, XOM, etc.) 
>>>belong with the model projects, not in jaxen core. 
>>>That way JDOM doesn't have to pay for the cost of everyone else's navigators and vice versa. 
>>>Also the project can keep the navigators in sync with their own releases.
>>>Could this code be added to JDOM2 instead?

It’s a great idea, but we are in bit urgency. 
It would be supportive, if we can release with these changes and in later release we can plan to move code to JDOM2.

**Comment by Rahman14354** [comment]
I have ran through all the tests locally and it is working as expected.

**Comment by elharo** [comment]
There are two paths forward I can see for this work. Both start by creating a new package for JDOM2 rather than changing the old one (which is still used and cannot be deleted without causing pain to users.) After that either:

1. Contribute this to the JDOM Project (if they're willing to take it)
2. Start a separate repository just for the JDOM 2 navigator (if they're not)

The Jaxen devs made an explicit decision several years ago not to accept new models into the core project because this causes dependency explosion. E.g. if we accepted this patch, everyone using Jaxen would now have a dependency on JDOM2, even if they have no actual JDOM2 code themselves.

**Pull request closed without merging**
